### ISSUE TITLE
Crash at open after update

### ISSUE THREAD

**Issue by argalad** [a-soll/native-twitch#17]
Hi, I was using the app with some random crashes but I could watch streams. After the new update the app crashes at startup with this report:
 
![Full report](https://user-images.githubusercontent.com/17321519/205940912-9e849f76-fdb0-4bfc-9efb-e1b855a3c6b6.png)

Thank you for your attention

**Comment by a-soll** [comment]
ok, looks like I can reproduce this on my VM. I should hopefully be able to fix this soon. thank you for the report.

**Comment by a-soll** [comment]
This should be resolved via [v2.0.1](https://github.com/a-soll/native-twitch/releases/tag/v2.0.1). Since your app doesn't start you'll have to delete it and download this version manually. Let me know if you still have issues though.

**Comment by argalad** [comment]
Unfortunately the app still crashes on startup, do you want me to post the report again?

**Comment by a-soll** [comment]
yes, post report. and you can confirm it's with the old version deleted, with new one manually installed?

**Comment by argalad** [comment]
Yes, I confirm I deleted the old version and manually installed the new one.
This is the report:
![CleanShot 2022-12-11 at 11 45 17@2x](https://user-images.githubusercontent.com/17321519/206899170-bfd44e8a-2f7a-42e2-8631-043ab57fe9ea.png)

**Comment by a-soll** [comment]
ok, was able to reproduce this after fully clearing cached data. I should be able to get this fixed soon.

**Comment by a-soll** [comment]
alright, I think I've fixed it. I put up [v2.0.2a](https://github.com/a-soll/native-twitch/releases/tag/v2.0.2a) as a test release for you to verify. If you're able to open it and run it, I'll make a formal release of it and close this issue. It looks like I missed setting a default value to one of the startup strings that I didn't catch due to Mac caching the app preferences.

**Comment by argalad** [comment]
Now it works great!
Thank you very much :D

**Comment by a-soll** [comment]
great! just fyi I didn't push any auto update config with it so not sure it'll update automatically. you should be able to run the old stable version now that you have your token cached, but otherwise just keep an eye out for the next release and grab it so your app continues to update automatically.

**Comment by argalad** [comment]
> great! just fyi I didn't push any auto update config with it so not sure it'll update automatically. you should be able to run the old stable version now that you have your token cached, but otherwise just keep an eye out for the next release and grab it so your app continues to update automatically.

Ok! I'll have an eye on it.

BTW, there's another little issue, when I'm writing in the chat, as I am a spanish native speaker, I use a lot of á, é, í...
and for some reason, whenever I type one of those accented vocals, they get written twice, so for instance if I write "estás" it will appear as "estáás" and it is a bit upsetting as I have to constantly delete one letter haha 
It is not something important so I don't mind if this does not get a fix right away, but just for you to know!

Thank you for your work.

**Comment by a-soll** [comment]
oh that's interesting about the chat. it's using just the regular pop out chat from Twitch.tv. does it happen in the website's pop out chat too? if not I can look into if it's different when embedded in the app.

**Comment by argalad** [comment]
No, in the website's chat, either in pop-up or embedded, it does not happen.

**Comment by a-soll** [comment]
ok good to know. I will look into this.
