### ISSUE TITLE
Refresh "Following" list? 

### ISSUE THREAD

**Issue by viewsourc3** [a-soll/native-twitch#21]
First of all, thank you for this app. I use a browser which is blocked by Twitch, so Native Twitch is a life saver. 

I was wondering if the app autorefreshes the "following" list, or if it is only up to the user to refresh that list. 

Would it be possible to add an option to refresh the list automatically? say every 10 minutes?

**Comment by a-soll** [comment]
Hey, I currently don't have it auto refreshing but I believe it could be added pretty easily. I do have the current stream info update every 45 seconds (so overlay will show changes in game/title/viewers), so should be able to do something similar for following list.

**Comment by viewsourc3** [comment]
sounds great! thanks
